export const PERM_CHILD_GROUP_CREATE = 'CHILD_GROUP_CREATE'; // Allowed to create child groups in this parent group
export const PERM_GROUP_DELETE = 'GROUP_DELETE'; // Allowed to delete the group
export const PERM_GROUP_INVITE = 'GROUP_INVITE'; // Allowed to invite others to the group
export const PERM_GROUP_ADMIN = 'GROUP_ADMIN'; // Allowed to kick members from the group and manage permissions (just invite for now) of other users in the group

export const PERM_GROUP_RW_MESSAGES = 'GROUP_RW_MESSAGES'; // Allowed to read an write messages in the group
export const PERM_GROUP_RW_LIST_EVENTS = 'GROUP_RW_LIST_EVENTS'; // Allowed to select and unselect list items and see when others do so.
export const PERM_GROUP_RW_LIST_ITEMS = 'GROUP_RW_LIST_ITEMS'; // Allowed to add and remove regular list items
export const PERM_GROUP_R_LIST_ITEMS = 'GROUP_R_LIST_ITEMS'; // Allowed to see regular list items
export const PERM_GROUP_RW_SECRET_LIST_ITEMS = 'GROUP_RW_SECRET_LIST_ITEMS'; // Allowed to see, add and remove secret list items

// All Group Permissions

export const PERM_ALL_LIST_GROUP = [
    PERM_CHILD_GROUP_CREATE,
    PERM_GROUP_DELETE,
    PERM_GROUP_INVITE,
    PERM_GROUP_ADMIN,
    PERM_GROUP_RW_MESSAGES,
    PERM_GROUP_RW_LIST_EVENTS,
    PERM_GROUP_RW_LIST_ITEMS,
    PERM_GROUP_R_LIST_ITEMS,
    PERM_GROUP_RW_SECRET_LIST_ITEMS,
];

export type TYPE_PERM_ALL_LIST_GROUP =
    | typeof PERM_CHILD_GROUP_CREATE
    | typeof PERM_GROUP_DELETE
    | typeof PERM_GROUP_INVITE
    | typeof PERM_GROUP_ADMIN
    | typeof PERM_GROUP_RW_MESSAGES
    | typeof PERM_GROUP_RW_LIST_EVENTS
    | typeof PERM_GROUP_RW_LIST_ITEMS
    | typeof PERM_GROUP_R_LIST_ITEMS
    | typeof PERM_GROUP_RW_SECRET_LIST_ITEMS;

// Child Group permissions

export const PERM_LIST_GROUP_CHILD = [
    PERM_GROUP_DELETE,
    PERM_GROUP_ADMIN,
    PERM_GROUP_INVITE,
    PERM_GROUP_RW_LIST_ITEMS,
    PERM_GROUP_RW_MESSAGES,
    PERM_GROUP_RW_LIST_EVENTS,
    PERM_GROUP_R_LIST_ITEMS,
    PERM_GROUP_RW_SECRET_LIST_ITEMS,
];
export type TYPE_PERM_LIST_GROUP_CHILD =
    | typeof PERM_GROUP_DELETE
    | typeof PERM_GROUP_INVITE
    | typeof PERM_GROUP_ADMIN
    | typeof PERM_GROUP_RW_MESSAGES
    | typeof PERM_GROUP_RW_LIST_EVENTS
    | typeof PERM_GROUP_RW_LIST_ITEMS
    | typeof PERM_GROUP_R_LIST_ITEMS
    | typeof PERM_GROUP_RW_SECRET_LIST_ITEMS;

export const listGroupChildBaseMemberPerms: TYPE_PERM_LIST_GROUP_CHILD[] = [
    PERM_GROUP_RW_MESSAGES,
    PERM_GROUP_RW_LIST_EVENTS,
    PERM_GROUP_R_LIST_ITEMS,
    PERM_GROUP_RW_SECRET_LIST_ITEMS,
];

export const listGroupChildBaseOwnerPerms: TYPE_PERM_LIST_GROUP_CHILD[] = [
    PERM_GROUP_DELETE,
    PERM_GROUP_ADMIN,
    PERM_GROUP_INVITE,
    PERM_GROUP_RW_LIST_ITEMS,
];

// Parent Group permissions

export const PERM_LIST_GROUP_PARENT = [
    PERM_CHILD_GROUP_CREATE,
    PERM_GROUP_DELETE,
    PERM_GROUP_INVITE,
    PERM_GROUP_ADMIN,
    PERM_GROUP_RW_MESSAGES,
    PERM_GROUP_RW_LIST_EVENTS,
    PERM_GROUP_RW_LIST_ITEMS,
    PERM_GROUP_R_LIST_ITEMS,
    PERM_GROUP_RW_SECRET_LIST_ITEMS,
];
export type TYPE_PERM_LIST_GROUP_PARENT =
    | typeof PERM_CHILD_GROUP_CREATE
    | typeof PERM_GROUP_DELETE
    | typeof PERM_GROUP_INVITE
    | typeof PERM_GROUP_ADMIN
    | typeof PERM_GROUP_RW_MESSAGES
    | typeof PERM_GROUP_RW_LIST_EVENTS
    | typeof PERM_GROUP_RW_LIST_ITEMS
    | typeof PERM_GROUP_R_LIST_ITEMS
    | typeof PERM_GROUP_RW_SECRET_LIST_ITEMS;

export const listGroupParentBaseMemberPerms: TYPE_PERM_LIST_GROUP_PARENT[] = [
    PERM_GROUP_RW_MESSAGES,
    PERM_GROUP_RW_LIST_EVENTS,
    PERM_GROUP_R_LIST_ITEMS,
    PERM_GROUP_RW_SECRET_LIST_ITEMS,
    PERM_CHILD_GROUP_CREATE,
];

export const listGroupParentBaseOwnerPerms: TYPE_PERM_LIST_GROUP_PARENT[] = [
    PERM_GROUP_DELETE,
    PERM_GROUP_ADMIN,
    PERM_GROUP_INVITE,
    PERM_GROUP_RW_LIST_ITEMS,
    PERM_CHILD_GROUP_CREATE,
];

// Single Group permissions

// BASIC_LIST

export const PERM_LIST_GROUP_SINGLE_BASIC_LIST = [
    PERM_GROUP_DELETE,
    PERM_GROUP_INVITE,
    PERM_GROUP_ADMIN,
    PERM_GROUP_RW_MESSAGES,
    PERM_GROUP_RW_LIST_EVENTS,
    PERM_GROUP_RW_LIST_ITEMS,
];
export type TYPE_PERM_LIST_GROUP_SINGLE_BASIC_LIST =
    | typeof PERM_GROUP_DELETE
    | typeof PERM_GROUP_INVITE
    | typeof PERM_GROUP_ADMIN
    | typeof PERM_GROUP_RW_MESSAGES
    | typeof PERM_GROUP_RW_LIST_EVENTS
    | typeof PERM_GROUP_RW_LIST_ITEMS;

export const listGroupSingleBasicListMemberPerms: TYPE_PERM_LIST_GROUP_SINGLE_BASIC_LIST[] = [
    PERM_GROUP_RW_MESSAGES,
    PERM_GROUP_RW_LIST_EVENTS,
    PERM_GROUP_RW_LIST_ITEMS,
];

export const listGroupSingleBasicListOwnerPerms: TYPE_PERM_LIST_GROUP_SINGLE_BASIC_LIST[] = [
    PERM_GROUP_DELETE,
    PERM_GROUP_INVITE,
    PERM_GROUP_ADMIN,
    PERM_GROUP_RW_MESSAGES,
    PERM_GROUP_RW_LIST_EVENTS,
    PERM_GROUP_RW_LIST_ITEMS,
];

// GIFT_LIST

export const PERM_LIST_GROUP_SINGLE_GIFT_LIST = [
    PERM_GROUP_DELETE,
    PERM_GROUP_INVITE,
    PERM_GROUP_ADMIN,
    PERM_GROUP_RW_MESSAGES,
    PERM_GROUP_RW_LIST_EVENTS,
    PERM_GROUP_RW_LIST_ITEMS,
    PERM_GROUP_R_LIST_ITEMS,
    PERM_GROUP_RW_SECRET_LIST_ITEMS,
];
export type TYPE_PERM_LIST_GROUP_SINGLE_GIFT_LIST =
    | typeof PERM_GROUP_DELETE
    | typeof PERM_GROUP_INVITE
    | typeof PERM_GROUP_ADMIN
    | typeof PERM_GROUP_RW_MESSAGES
    | typeof PERM_GROUP_RW_LIST_EVENTS
    | typeof PERM_GROUP_RW_LIST_ITEMS
    | typeof PERM_GROUP_R_LIST_ITEMS
    | typeof PERM_GROUP_RW_SECRET_LIST_ITEMS;

export const listGroupSingleGiftListMemberPerms: TYPE_PERM_LIST_GROUP_SINGLE_GIFT_LIST[] = [
    PERM_GROUP_RW_MESSAGES,
    PERM_GROUP_RW_LIST_EVENTS,
    PERM_GROUP_R_LIST_ITEMS,
    PERM_GROUP_RW_SECRET_LIST_ITEMS,
];

export const listGroupSingleGiftListOwnerPerms: TYPE_PERM_LIST_GROUP_SINGLE_GIFT_LIST[] = [
    PERM_GROUP_DELETE,
    PERM_GROUP_ADMIN,
    PERM_GROUP_INVITE,
    PERM_GROUP_RW_LIST_ITEMS,
];
