export const PERM_CHILD_GROUP_CREATE = 'CHILD_GROUP_CREATE';
export const PERM_GROUP_DELETE = 'GROUP_DELETE';
export const PERM_GROUP_INVITE = 'GROUP_INVITE';
export const PERM_GROUP_ADMIN = 'GROUP_ADMIN';

export const PERM_ALL_LIST_GROUP = [PERM_CHILD_GROUP_CREATE, PERM_GROUP_DELETE, PERM_GROUP_INVITE, PERM_GROUP_ADMIN];

export type TYPE_PERM_ALL_LIST_GROUP =
    | typeof PERM_CHILD_GROUP_CREATE
    | typeof PERM_GROUP_DELETE
    | typeof PERM_GROUP_INVITE
    | typeof PERM_GROUP_ADMIN;
