// Users
export const VALIDATION_USER_DISPLAY_NAME_MIN_LENGTH = 1;
export const VALIDATION_USER_DISPLAY_NAME_MAX_LENGTH = 16;
export const VALIDATION_USER_EMAIL_MIN_LENGTH = 1;
export const VALIDATION_USER_EMAIL_MAX_LENGTH = 254;
export const VALIDATION_USER_PASSWORD_MIN_LENGTH = 8;
export const VALIDATION_USER_PASSWORD_MAX_LENGTH = 200;
export const VALIDATION_USER_PASSWORD_MIN_UPPERCASE = 1;
export const VALIDATION_USER_PASSWORD_MIN_LOWERCASE = 1;
export const VALIDATION_USER_PASSWORD_MIN_NUMBER = 1;
export const VALIDATION_USER_PASSWORD_MIN_SYMBOL = 0;

// Groups
export const VALIDATION_GROUP_NAME_MIN_LENGTH = 1;
export const VALIDATION_GROUP_NAME_MAX_LENGTH = 30;

// Items
export const VALIDATION_ITEM_BODY_MIN_LENGTH = 1;
export const VALIDATION_ITEM_BODY_MAX_LENGTH = 200;
export const VALIDATION_ITEM_LINK_MIN_LENGTH = 1;
export const VALIDATION_ITEM_LINK_MAX_LENGTH = 1000;

// Messages
export const VALIDATION_MESSAGE_MIN_LENGTH = 1;
export const VALIDATION_MESSAGE_MAX_LENGTH = 200;
